TrajectoryPlannerROS:

  # Robot configuration parameters
  max_vel_x: 0.5
  min_vel_x: 0.01

  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_theta: 0.6
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  holonomic_robot: false

# Goal Tolerance Parameters
  xy_goal_tolerance: 1.0 #default: 0.05
  yaw_goal_tolerance: 1.0 #default: 0.1

# Forward Simulation Parameters
  sim_time: 1.0
  vx_samples: 5
  vtheta_samples: 20
  sim_granularity: 0.05

# Trajectory Scoring Parameters
  meter_scoring: true
  global_frame_id: odom

