max_obstacle_height: 0.5  # assume something like an arm is mounted on top of the robot

robot_radius: 0.3 # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

