footprint: [[-0.25,-0.25], [0.25,-0.25], [0.25,0.25], [-0.25,0.25]]

obstacle_range: 3.0
raytrace_range: 3.5
inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

